name: hello_flutter
description: SnowRobot controller app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # iOS icons
  cupertino_icons: ^1.0.8
  # UI + routing
  google_fonts: ^6.2.1
  go_router: ^14.2.0
  # State management
  flutter_riverpod: ^2.5.1
  # Bluetooth (BLE, подходит для iPhone)
  flutter_blue_plus: ^2.0.2
  # Permissions (Android)
  permission_handler: ^12.0.1
  device_preview: ^1.3.1
  # Local storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
